name: 💡 Vocabulary improvement
description: Suggest a change or addition
title: "💡 <title>"
labels: ["Enhancement"]
body:
- type: textarea
  id: description
  attributes:
    label: Description
    description: What do you propose?
  validations:
    required: false
